# Generated by Django 2.1.2 on 2018-10-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181027_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='expirience',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
